// <auto-generated />
using System;
using Meta_xi.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meta_xi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260512055644_AddPlanDetailsAndSeed")]
    partial class AddPlanDetailsAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Meta_xi.Application.DepositHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DepositHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.Plan", b =>
                {
                    b.Property<int>("IDPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyBenefit")
                        .HasColumnType("REAL");

                    b.Property<double?>("DailyProfitPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("DaysActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalBenefit")
                        .HasColumnType("REAL");

                    b.HasKey("IDPlan");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            IDPlan = 1,
                            DailyBenefit = 2000.0,
                            DailyProfitPercentage = 4.0,
                            DaysActive = 30,
                            Description = "Un resort de golf icónico y legendario en la costa escocesa. Turismo de lujo internacional.",
                            ImageUrl = "/plans/trump-turnberry.webp",
                            MaxQuantity = 100,
                            Name = "Trump Turnberry",
                            Price = 50000.0,
                            TotalBenefit = 60000.0
                        },
                        new
                        {
                            IDPlan = 2,
                            DailyBenefit = 9000.0,
                            DailyProfitPercentage = 6.0,
                            DaysActive = 30,
                            Description = "El rascacielos insignia en la Quinta Avenida. Alquiler de espacios comerciales y rentas de oficinas de lujo.",
                            ImageUrl = "/plans/trump-tower.webp",
                            MaxQuantity = 100,
                            Name = "Trump Tower",
                            Price = 150000.0,
                            TotalBenefit = 270000.0
                        },
                        new
                        {
                            IDPlan = 3,
                            DailyBenefit = 19200.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 30,
                            Description = "Un club privado histórico y la residencia principal de Trump.",
                            ImageUrl = "/plans/mar-a-lago.webp",
                            MaxQuantity = 100,
                            Name = "Mar-a-Lago",
                            Price = 240000.0,
                            TotalBenefit = 576000.0
                        },
                        new
                        {
                            IDPlan = 4,
                            DailyBenefit = 31500.0,
                            DailyProfitPercentage = 9.0,
                            DaysActive = 30,
                            Description = "Un edificio de oficinas de 71 pisos en el distrito financiero. Arrendamiento comercial.",
                            ImageUrl = "/plans/40-wall-street.webp",
                            MaxQuantity = 100,
                            Name = "40 Wall Street",
                            Price = 350000.0,
                            TotalBenefit = 945000.0
                        },
                        new
                        {
                            IDPlan = 5,
                            DailyBenefit = 50000.0,
                            DailyProfitPercentage = 10.0,
                            DaysActive = 30,
                            Description = "Un casino de juegos tragamonedas, poker y mucho más.",
                            ImageUrl = "/plans/trump-casino.webp",
                            MaxQuantity = 100,
                            Name = "Trump Casino",
                            Price = 500000.0,
                            TotalBenefit = 1500000.0
                        },
                        new
                        {
                            IDPlan = 6,
                            DailyBenefit = 96000.0,
                            DailyProfitPercentage = 12.0,
                            DaysActive = 30,
                            Description = "Uno de los edificios más altos y valiosos de la costa oeste. Alquiler de oficinas.",
                            ImageUrl = "/plans/555-california.webp",
                            MaxQuantity = 100,
                            Name = "555 California Street",
                            Price = 800000.0,
                            TotalBenefit = 2880000.0
                        },
                        new
                        {
                            IDPlan = 7,
                            DailyBenefit = 180000.0,
                            DailyProfitPercentage = 15.0,
                            DaysActive = 30,
                            Description = "Un rascacielos de uso mixto junto al río Chicago. Hotel y condominios.",
                            ImageUrl = "/plans/trump-chicago.webp",
                            MaxQuantity = 100,
                            Name = "Trump International Hotel & Tower Chicago",
                            Price = 1200000.0,
                            TotalBenefit = 5400000.0
                        },
                        new
                        {
                            IDPlan = 8,
                            DailyBenefit = 1500000.0,
                            DailyProfitPercentage = 30.0,
                            DaysActive = 30,
                            Description = "Una torre dorada hotel y condo-hotel. Operación hotelera y comisiones.",
                            ImageUrl = "/plans/trump-vegas.webp",
                            MaxQuantity = 100,
                            Name = "Trump International Hotel Las Vegas",
                            Price = 5000000.0,
                            TotalBenefit = 45000000.0
                        });
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel1s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel2s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel3s");
                });

            modelBuilder.Entity("Meta_xi.Application.TaskRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActivateAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskRegisters");
                });

            modelBuilder.Entity("Meta_xi.Application.UpdatePlansForUser", b =>
                {
                    b.Property<int>("IDUpdatePlansForUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AcumulatedBenefitperHour")
                        .HasColumnType("REAL");

                    b.Property<double>("AcumulatedTotalBenefit")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUpdatePlansForUser");

                    b.ToTable("UpdatePlansForUser");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WalletIdWallet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WalletIdWallet");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Meta_xi.Application.UserPlans", b =>
                {
                    b.Property<int>("IDBuyPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDBuyPlan");

                    b.ToTable("UserPlans");
                });

            modelBuilder.Entity("Meta_xi.Application.Wallet", b =>
                {
                    b.Property<int>("IdWallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalRecharged")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalWithdrawn")
                        .HasColumnType("REAL");

                    b.HasKey("IdWallet");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Meta_xi.Application.WithdrawalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Fee")
                        .HasColumnType("REAL");

                    b.Property<float>("NetAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel1s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel2s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel3s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.HasOne("Meta_xi.Application.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletIdWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Navigation("referLevel1s");

                    b.Navigation("referLevel2s");

                    b.Navigation("referLevel3s");
                });
#pragma warning restore 612, 618
        }
    }
}
