// <auto-generated />
using System;
using Meta_xi.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meta_xi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260509221540_AddWalletAndHistoryTracking")]
    partial class AddWalletAndHistoryTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Meta_xi.Application.DepositHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DepositHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.Plan", b =>
                {
                    b.Property<int>("IDPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyBenefit")
                        .HasColumnType("REAL");

                    b.Property<int>("DaysActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalBenefit")
                        .HasColumnType("REAL");

                    b.HasKey("IDPlan");

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel1s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel2s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel3s");
                });

            modelBuilder.Entity("Meta_xi.Application.TaskRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActivateAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskRegisters");
                });

            modelBuilder.Entity("Meta_xi.Application.UpdatePlansForUser", b =>
                {
                    b.Property<int>("IDUpdatePlansForUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AcumulatedBenefitperHour")
                        .HasColumnType("REAL");

                    b.Property<double>("AcumulatedTotalBenefit")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUpdatePlansForUser");

                    b.ToTable("UpdatePlansForUser");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WalletIdWallet")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WalletIdWallet");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Meta_xi.Application.UserPlans", b =>
                {
                    b.Property<int>("IDBuyPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDBuyPlan");

                    b.ToTable("UserPlans");
                });

            modelBuilder.Entity("Meta_xi.Application.Wallet", b =>
                {
                    b.Property<int>("IdWallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalRecharged")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalWithdrawn")
                        .HasColumnType("REAL");

                    b.HasKey("IdWallet");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Meta_xi.Application.WithdrawalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Fee")
                        .HasColumnType("REAL");

                    b.Property<float>("NetAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel1s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel2s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel3s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.HasOne("Meta_xi.Application.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletIdWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Navigation("referLevel1s");

                    b.Navigation("referLevel2s");

                    b.Navigation("referLevel3s");
                });
#pragma warning restore 612, 618
        }
    }
}
