// <auto-generated />
using System;
using Meta_xi.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meta_xi.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Meta_xi.Application.BotPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BuyPercentage")
                        .HasColumnType("REAL");

                    b.Property<decimal>("DailyProfitEstimate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exchanges")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FreeTierMaxUses")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFreeTier")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SellPercentage")
                        .HasColumnType("REAL");

                    b.Property<int?>("StockMax")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalProfitEstimate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingPair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("WinRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BotPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyPercentage = 54.200000000000003,
                            DailyProfitEstimate = 500m,
                            Description = "Bot de alta frecuencia para trading de Bitcoin. Aprovecha micro-movimientos del mercado con alta efectividad. Uso gratuito limitado.",
                            DurationDays = 7,
                            Exchanges = "Binance,KuCoin",
                            FreeTierMaxUses = 1,
                            IconColor = "#00c853",
                            ImageUrl = "/bots/free-bot.webp",
                            IsFreeTier = true,
                            Name = "Free Bot",
                            Price = 0m,
                            SellPercentage = 45.799999999999997,
                            StockMax = 1,
                            TotalProfitEstimate = 3500m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.71999999999999997
                        },
                        new
                        {
                            Id = 2,
                            BuyPercentage = 59.100000000000001,
                            DailyProfitEstimate = 900m,
                            Description = "Estrategia de grid trading en Ethereum con enfoque en exchanges asiáticos. Opera en rangos de precio predefinidos.",
                            DurationDays = 228,
                            Exchanges = "Bybit,MEXC",
                            IconColor = "#ffa929",
                            ImageUrl = "/bots/byte-bot.webp",
                            IsFreeTier = false,
                            Name = "Byte Bot",
                            Price = 30000m,
                            SellPercentage = 40.899999999999999,
                            StockMax = 2,
                            TotalProfitEstimate = 205200m,
                            TradingPair = "ETH/USDT",
                            WinRate = 0.68000000000000005
                        },
                        new
                        {
                            Id = 3,
                            BuyPercentage = 61.899999999999999,
                            DailyProfitEstimate = 1500m,
                            Description = "Bot institucional de alto rendimiento para Ethereum. Diseñado para mercados con alta liquidez.",
                            DurationDays = 240,
                            Exchanges = "OKX,Gate.io",
                            IconColor = "#e9ecef",
                            ImageUrl = "/bots/cronos-bot.webp",
                            IsFreeTier = false,
                            Name = "Cronos Bot",
                            Price = 50000m,
                            SellPercentage = 38.100000000000001,
                            StockMax = 2,
                            TotalProfitEstimate = 360000m,
                            TradingPair = "ETH/USDT",
                            WinRate = 0.75
                        },
                        new
                        {
                            Id = 4,
                            BuyPercentage = 57.600000000000001,
                            DailyProfitEstimate = 3300m,
                            Description = "Especializado en Solana con estrategia de momentum. Ideal para capturar movimientos fuertes del mercado.",
                            DurationDays = 260,
                            Exchanges = "Coinbase,Kraken",
                            IconColor = "#0052ff",
                            ImageUrl = "/bots/abstrar-bot.webp",
                            IsFreeTier = false,
                            Name = "Abstrar Bot",
                            Price = 100000m,
                            SellPercentage = 42.399999999999999,
                            StockMax = 2,
                            TotalProfitEstimate = 858000m,
                            TradingPair = "SOL/USDT",
                            WinRate = 0.69999999999999996
                        },
                        new
                        {
                            Id = 5,
                            BuyPercentage = 64.5,
                            DailyProfitEstimate = 5100m,
                            Description = "Bot premium para Bitcoin con múltiples nodos de ejecución. Máxima velocidad en operaciones de alta frecuencia.",
                            DurationDays = 290,
                            Exchanges = "Bitget,HTX,Binance",
                            IconColor = "#00f0ff",
                            ImageUrl = "/bots/atlas-bot.webp",
                            IsFreeTier = false,
                            Name = "Atlas Bot",
                            Price = 150000m,
                            SellPercentage = 35.5,
                            StockMax = 2,
                            TotalProfitEstimate = 1479000m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.78000000000000003
                        },
                        new
                        {
                            Id = 6,
                            BuyPercentage = 52.100000000000001,
                            DailyProfitEstimate = 10800m,
                            Description = "Bot de arbitraje entre exchanges coreanos y globales. Aprovecha diferencias de precio en tiempo real.",
                            DurationDays = 300,
                            Exchanges = "Upbit,Binance",
                            IconColor = "#004fff",
                            ImageUrl = "/bots/nexus-bot.webp",
                            IsFreeTier = false,
                            Name = "Nexus Bot",
                            Price = 300000m,
                            SellPercentage = 47.899999999999999,
                            StockMax = 1,
                            TotalProfitEstimate = 3240000m,
                            TradingPair = "ETH/USDT",
                            WinRate = 0.76000000000000001
                        },
                        new
                        {
                            Id = 7,
                            BuyPercentage = 56.399999999999999,
                            DailyProfitEstimate = 18000m,
                            Description = "Estrategia de scalping avanzada para Bitcoin. Múltiples operaciones por día con gestión de riesgo optimizada.",
                            DurationDays = 320,
                            Exchanges = "KuCoin,Gate.io",
                            IconColor = "#00b57a",
                            ImageUrl = "/bots/nova-bot.webp",
                            IsFreeTier = false,
                            Name = "Nova Bot",
                            Price = 500000m,
                            SellPercentage = 43.600000000000001,
                            StockMax = 2,
                            TotalProfitEstimate = 5760000m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.80000000000000004
                        },
                        new
                        {
                            Id = 8,
                            BuyPercentage = 62.799999999999997,
                            DailyProfitEstimate = 29600m,
                            Description = "Bot de trading algorítmico de última generación. Machine learning aplicado al análisis de mercado.",
                            DurationDays = 340,
                            Exchanges = "Bybit,OKX",
                            IconColor = "#ffa929",
                            ImageUrl = "/bots/optix-bot.webp",
                            IsFreeTier = false,
                            Name = "Optix Bot",
                            Price = 800000m,
                            SellPercentage = 37.200000000000003,
                            StockMax = 1,
                            TotalProfitEstimate = 10064000m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.81999999999999995
                        },
                        new
                        {
                            Id = 9,
                            BuyPercentage = 67.099999999999994,
                            DailyProfitEstimate = 38000m,
                            Description = "Sistema institucional de trading cuantitativo. Estrategias de alta frecuencia con ejecución en milisegundos.",
                            DurationDays = 380,
                            Exchanges = "MEXC,Coinbase,Kraken",
                            IconColor = "#00b0ff",
                            ImageUrl = "/bots/sigma-bot.webp",
                            IsFreeTier = false,
                            Name = "Sigma Bot",
                            Price = 1000000m,
                            SellPercentage = 32.899999999999999,
                            StockMax = 1,
                            TotalProfitEstimate = 14440000m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.84999999999999998
                        },
                        new
                        {
                            Id = 10,
                            BuyPercentage = 69.400000000000006,
                            DailyProfitEstimate = 62400m,
                            Description = "El bot más avanzado de nuestra plataforma. Estrategia multi-exchange con liquidez profunda y ejecución ultra-rápida.",
                            DurationDays = 420,
                            Exchanges = "HTX,Upbit,Bitget",
                            IconColor = "#1a6ed1",
                            ImageUrl = "/bots/flux-bot.webp",
                            IsFreeTier = false,
                            Name = "Flux Bot",
                            Price = 1600000m,
                            SellPercentage = 30.600000000000001,
                            StockMax = 1,
                            TotalProfitEstimate = 26208000m,
                            TradingPair = "BTC/USDT",
                            WinRate = 0.88
                        });
                });

            modelBuilder.Entity("Meta_xi.Application.DepositHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrdenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DepositHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.Mission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Gift")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ref")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gift = 1000f,
                            ImageUrl = "/missions/invite-5.webp",
                            Ref = 5,
                            Title = "Invita 5 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Gift = 3000f,
                            ImageUrl = "/missions/invite-15.webp",
                            Ref = 15,
                            Title = "Invita 15 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Gift = 4000f,
                            ImageUrl = "/missions/invite-20.webp",
                            Ref = 20,
                            Title = "Invita 20 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Gift = 6000f,
                            ImageUrl = "/missions/invite-30.webp",
                            Ref = 30,
                            Title = "Invita 30 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Gift = 8000f,
                            ImageUrl = "/missions/invite-40.webp",
                            Ref = 40,
                            Title = "Invita 40 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Gift = 10000f,
                            ImageUrl = "/missions/invite-50.webp",
                            Ref = 50,
                            Title = "Invita 50 nuevos amigos",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Gift = 2000f,
                            ImageUrl = "/missions/invite-10p.webp",
                            Ref = 10,
                            Title = "Invita 10 nuevos amigos",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Gift = 30000f,
                            ImageUrl = "/missions/invite-100.webp",
                            Ref = 100,
                            Title = "Invita 100 nuevos amigos",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Gift = 40000f,
                            ImageUrl = "/missions/invite-250.webp",
                            Ref = 250,
                            Title = "Invita 250 nuevos amigos",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Gift = 60000f,
                            ImageUrl = "/missions/invite-350.webp",
                            Ref = 350,
                            Title = "Invita 350 nuevos amigos",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Gift = 80000f,
                            ImageUrl = "/missions/invite-450.webp",
                            Ref = 450,
                            Title = "Invita 450 nuevos amigos",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Gift = 100000f,
                            ImageUrl = "/missions/invite-500.webp",
                            Ref = 500,
                            Title = "Invita 500 nuevos amigos",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Meta_xi.Application.Plan", b =>
                {
                    b.Property<int>("IDPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DailyBenefit")
                        .HasColumnType("REAL");

                    b.Property<double?>("DailyProfitPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("DaysActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalBenefit")
                        .HasColumnType("REAL");

                    b.HasKey("IDPlan");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            IDPlan = 1,
                            DailyBenefit = 4000.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 30,
                            Description = "Un resort de golf icónico y legendario en la costa escocesa. Turismo de lujo internacional.",
                            ImageUrl = "/plans/trump-turnberry.webp",
                            MaxQuantity = 100,
                            Name = "Trump Turnberry",
                            Price = 50000.0,
                            TotalBenefit = 120000.0
                        },
                        new
                        {
                            IDPlan = 2,
                            DailyBenefit = 8000.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 30,
                            Description = "El rascacielos insignia en la Quinta Avenida. Alquiler de espacios comerciales y rentas de oficinas de lujo.",
                            ImageUrl = "/plans/trump-tower.webp",
                            MaxQuantity = 100,
                            Name = "Trump Tower",
                            Price = 100000.0,
                            TotalBenefit = 240000.0
                        },
                        new
                        {
                            IDPlan = 3,
                            DailyBenefit = 12800.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 45,
                            Description = "Un club privado histórico y la residencia principal de Trump.",
                            ImageUrl = "/plans/mar-a-lago.webp",
                            MaxQuantity = 100,
                            Name = "Mar-a-Lago",
                            Price = 160000.0,
                            TotalBenefit = 576000.0
                        },
                        new
                        {
                            IDPlan = 4,
                            DailyBenefit = 15000.0,
                            DailyProfitPercentage = 6.0,
                            DaysActive = 50,
                            Description = "Un edificio de oficinas de 71 pisos en el distrito financiero. Arrendamiento comercial.",
                            ImageUrl = "/plans/40-wall-street.webp",
                            MaxQuantity = 100,
                            Name = "40 Wall Street",
                            Price = 250000.0,
                            TotalBenefit = 750000.0
                        },
                        new
                        {
                            IDPlan = 5,
                            DailyBenefit = 21000.0,
                            DailyProfitPercentage = 6.0,
                            DaysActive = 50,
                            Description = "Un casino de juegos tragamonedas, poker y mucho más.",
                            ImageUrl = "/plans/trump-casino.webp",
                            MaxQuantity = 100,
                            Name = "Trump Casino",
                            Price = 350000.0,
                            TotalBenefit = 1050000.0
                        },
                        new
                        {
                            IDPlan = 6,
                            DailyBenefit = 40000.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 50,
                            Description = "Uno de los edificios más altos y valiosos de la costa oeste. Alquiler de oficinas.",
                            ImageUrl = "/plans/555-california.webp",
                            MaxQuantity = 100,
                            Name = "555 California Street",
                            Price = 500000.0,
                            TotalBenefit = 2000000.0
                        },
                        new
                        {
                            IDPlan = 7,
                            DailyBenefit = 64000.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 50,
                            Description = "Un rascacielos de uso mixto junto al río Chicago. Hotel y condominios.",
                            ImageUrl = "/plans/trump-chicago.webp",
                            MaxQuantity = 100,
                            Name = "Trump International Hotel & Tower Chicago",
                            Price = 800000.0,
                            TotalBenefit = 3200000.0
                        },
                        new
                        {
                            IDPlan = 8,
                            DailyBenefit = 96000.0,
                            DailyProfitPercentage = 8.0,
                            DaysActive = 50,
                            Description = "Una torre dorada hotel y condo-hotel. Operación hotelera y comisiones.",
                            ImageUrl = "/plans/trump-vegas.webp",
                            MaxQuantity = 100,
                            Name = "Trump International Hotel Las Vegas",
                            Price = 1200000.0,
                            TotalBenefit = 4800000.0
                        });
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel1s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel2s");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.Property<int>("IDReferLevel1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDUserReferrer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniqueCodeReFerred")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueCodeReferrer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDReferLevel1");

                    b.HasIndex("IDUserReferrer");

                    b.ToTable("ReferLevel3s");
                });

            modelBuilder.Entity("Meta_xi.Application.TaskRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActivateAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TaskRegisters");
                });

            modelBuilder.Entity("Meta_xi.Application.UpdatePlansForUser", b =>
                {
                    b.Property<int>("IDUpdatePlansForUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AcumulatedBenefitperHour")
                        .HasColumnType("REAL");

                    b.Property<double>("AcumulatedTotalBenefit")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDUpdatePlansForUser");

                    b.ToTable("UpdatePlansForUser");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WalletIdWallet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WithdrawPassword")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletIdWallet");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Meta_xi.Application.UserActivePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AccumulatedProfit")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("TEXT");

                    b.Property<int>("BotPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastTradeAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BotPlanId");

                    b.ToTable("UserActivePlans");
                });

            modelBuilder.Entity("Meta_xi.Application.UserFreeBotUsage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BotPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FirstUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserFreeBotUsages");
                });

            modelBuilder.Entity("Meta_xi.Application.UserMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("Email", "MissionId")
                        .IsUnique();

                    b.ToTable("UserMissions");
                });

            modelBuilder.Entity("Meta_xi.Application.UserPlans", b =>
                {
                    b.Property<int>("IDBuyPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatePlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamePlan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Percentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IDBuyPlan");

                    b.ToTable("UserPlans");
                });

            modelBuilder.Entity("Meta_xi.Application.Wallet", b =>
                {
                    b.Property<int>("IdWallet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TotalRecharged")
                        .HasColumnType("REAL");

                    b.Property<float>("TotalWithdrawn")
                        .HasColumnType("REAL");

                    b.HasKey("IdWallet");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Meta_xi.Application.WithdrawalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Fee")
                        .HasColumnType("REAL");

                    b.Property<float>("NetAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("OrdenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WithdrawalHistories");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel1", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel1s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel2", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel2s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.ReferLevel3", b =>
                {
                    b.HasOne("Meta_xi.Application.User", "User")
                        .WithMany("referLevel3s")
                        .HasForeignKey("IDUserReferrer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.HasOne("Meta_xi.Application.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletIdWallet");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Meta_xi.Application.UserActivePlan", b =>
                {
                    b.HasOne("Meta_xi.Application.BotPlan", "BotPlan")
                        .WithMany()
                        .HasForeignKey("BotPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BotPlan");
                });

            modelBuilder.Entity("Meta_xi.Application.UserMission", b =>
                {
                    b.HasOne("Meta_xi.Application.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");
                });

            modelBuilder.Entity("Meta_xi.Application.User", b =>
                {
                    b.Navigation("referLevel1s");

                    b.Navigation("referLevel2s");

                    b.Navigation("referLevel3s");
                });
#pragma warning restore 612, 618
        }
    }
}
